# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Distribution

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  Linux_Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORMS: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: set version
      run: cat src/version.go && echo "package main
const Version = \"${{ steps.get_version.outputs.VERSION }}\"" > src/version.go && cat src/version.go

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true
        cache-dependency-path: go.sum

    - name: Build_Binary
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.PLATFORMS }} go build -o server-linux-${{ matrix.PLATFORMS }} -ldflags '-s -w --extldflags "-static -fpic"' ./src/
    - name: Pack
      run: 
        tar -czvf server-linux-${{ matrix.PLATFORMS }}.tar.gz server-linux-${{ matrix.PLATFORMS }} config.json version.txt README.md
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
          server-linux-${{ matrix.PLATFORMS }}.tar.gz
